name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt-get install cmake gettext libgtk-3-dev libappindicator3-dev libxi-dev
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. && make
